### ISSUE TITLE
 value of "label_size?  thanks!

### ISSUE THREAD

**Issue by mengshiyu0109** [xinge008/Cylinder3D#100]
Dear author
thanks for sharing, when using the  function in the img ,I am confused,
If  I only have the 3 classes, 0:backgroud ,1: car ,2 :people , 
I need change the   value of "label_size"  to 3? 

![图片](https://user-images.githubusercontent.com/88700988/143264111-e0819704-be0a-46c4-a5b2-7c4fcb1b8621.png)

**Comment by xinge008** [comment]
This value is set according to the label mapping of semanticKITTI; you can set it based on your dataset. 

If you only have three categories, it should be 3;
