### ISSUE TITLE
ill-formed sparse convolution network in Cylinder3D

### ISSUE THREAD

**Issue by FindDefinition** [xinge008/Cylinder3D#102]
Hi, I'm developer of spconv.
this [cylinder module](https://github.com/xinge008/Cylinder3D/blob/master/network/segmentator_3d_asymm_spconv.py#L174) is definitely ill-formed sparse convolution. 
if subm layers share same key, they must have same spatial structure (indices), same kernel size and same dilation.
If two subm layers have different kernel size or dilation or spatial structure, you must assign a different indice key.
In your ```UpBlock```, you use same indice key in three subm layers but the kernel size is different, so in spconv 1.x, the ```conv2``` and ```conv3``` actually run ```conv1``` with different weight. the ```conv3```only use 9 of 27 weight during calculation.
I plan to add some auto-reuse mechanism in future.

**Comment by xinge008** [comment]
Thanks for your reminder. I will check and fix it.
