### ISSUE TITLE
Inference code to evaluate model on pointcloud files

### ISSUE THREAD

**Issue by ChidanandKumarKS** [xinge008/Cylinder3D#11]
@xinge008 
Do you have Inference code to evaluate model on pointcloud files?

**Comment by xinge008** [comment]
@ChidanandKumarKS  the inference code is shown in train_cylinder_asym.py (see val part). For one point cloud input, you can modify the dataloader to suit your requirements.

**Comment by wakasu** [comment]
> @xinge008
> Do you have Inference code to evaluate model on pointcloud files?

Hey there!

Did you find the way to perform inference? 
 i am trying to predict a pointcloud and would really appreciate if you can provide me with your code or some pointers.

**Comment by abhigoku10** [comment]
@xinge008 i have the inference code shall i create a pull request ??

**Comment by wakasu** [comment]
> @xinge008 i have the inference code shall i create a pull request ??

Hey!
could you please share your code on google drive or some similar service?
the pull request might take some time and i really need to have this done by tomorrow. 

would really appreciate your help.

**Comment by xinge008** [comment]
@wakasu 

For inference on SemanticKITTI or nuScenes, I have provided the code example in https://github.com/xinge008/Cylinder3D/blob/master/train_cylinder_asym.py#L82-L107;

For testing a point cloud from other source, you can modify the dataloader with your own path, like https://github.com/xinge008/Cylinder3D/blob/master/dataloader/pc_dataset.py#L49;

If it is urgent, maybe you can directly use the code from @abhigoku10 ;

**Comment by wakasu** [comment]
@xinge008 
Thanks for the pointers.
it will take time to modify the code to use our dataset and that's the thing i don't have right now. lol

will wait for @abhigoku10 to send his code.

**Comment by abhigoku10** [comment]
@wakasu  share your mail id so that i can send it across

**Comment by chowkamlee81** [comment]
@abhigoku10 
Can you also send me to my mail id : chidaimagepks@gmail.com

**Comment by wakasu** [comment]
@abhigoku10

wakasu@outlook.com

Thanks a lot for your help

**Comment by abhigoku10** [comment]
@wakasu @chowkamlee81  i have uploaded it on git  https://github.com/abhigoku10/Cylinder3D_PC.git

**Comment by vaydingul** [comment]
Hi @abhigoku10,
Can you also send your inference code to me?

vaydingul20@ku.edu.tr

Thx in advance!

**Comment by manuel-88** [comment]
Hi @abhigoku10 ,

could you also send me the inference code? 

mawiest88@gmail.com

Thank you very much.

**Comment by adrianezquerro** [comment]
Hi @abhigoku10 ,
I arrive much later but it would be helpful if you also send me your inference code. Could you?

adrian@panoimagen.com

Thank you very much!

**Comment by didxorkd** [comment]
Hi @abhigoku10 
I arrived late, but could you send me the inference code? it would be really helpful.
didxorkd@snu.ac.kr
Thank you very much!
