### ISSUE TITLE
spconv error shape in SubMConv3d

### ISSUE THREAD

**Issue by Leozyc-waseda** [xinge008/Cylinder3D#121]
I think this is due to the problem caused by the upgrade of Spcony to 2.0. The official has announced that it no longer supports spcony 1.x. Have you considered upgrading to spcony 2.0?

**Comment by nubertj** [comment]
+1

**Comment by Leozyc-waseda** [comment]
@nubertj 
I already solved this.
```

/****************************spconv1********************************************/
conda create -n spconv1 python==3.6 pytorch=1.2 torchvision cudatoolkit=9.2

$ git clone https://github.com/traveller59/spconv.git --recursive
$ cd spconv/
$ git checkout 8da6f96


$ cd third_party/
$ git clone https://github.com/pybind/pybind11.git
$ cd pybind11/
$ git checkout 085a294

$ cd ../..
$ python setup.py bdist_wheel

$ cd ./dist 
$ pip install xxx.whl to install spconv.
```

hope it helps.

**Comment by nubertj** [comment]
Thanks for your reply.
Howeever, I don't quite understand how this addresses our issue?
After upgrading to spconv2 there is this mentioned error. We could fix it, but then the old pre-trained models do not work anymore.

**Comment by chenhaomingbob** [comment]
> 



> Thanks for your reply. Howeever, I don't quite understand how this addresses our issue? After upgrading to spconv2 there is this mentioned error. We could fix it, but then the old pre-trained models do not work anymore.

Meet the same error after using spconv2.x.
