### ISSUE TITLE
About visualization of voxelization 

### ISSUE THREAD

**Issue by artofstate** [xinge008/Cylinder3D#129]
Hi @xinge008 ,How did you decide the resolution of voxelization?   Have you make some visualization about the partation effect picture? In a word ,i want to know how to show the points and the partation boxes  at the same time?

**Comment by xinge008** [comment]
The resolution of cylinder voxelization is 480*360, corresponding to 10cm in the distance and 1 degree; For visualization, you can use ring and ray to split the point cloud.
