### ISSUE TITLE
Thanks for your great work. But it seems that there are many mismatches in the code.

### ISSUE THREAD

**Issue by l9761116** [xinge008/Cylinder3D#136]
I'm new to AI algos. So it's a bit difficult for me when the code cannot run successfully, to find the problems and modify them.  Since your work is such a hot choice in Semantic KITTI task, I really see the good if these issues can be fixed. 

Basically, I met three biggest problems, all in 'segmentator_3d_asymm_spconv.py'.
 
First, 
```
x.feature = Func(x.feature)
```
is an incompatible line. There are many of these lines in the file.
 
Second, I met an error
>ValueError: subm with same indice_key must have same kernel size, expect [1, 3, 3], this layer [3, 1, 3]

I looked through the issues and found that someone else also met this problem. I guess this is because you have uploaded different versions of the algorithm. But I'd appreciate if you could fix this mismatch.
 
Last, since spconv 1.x is deprecated now, it'll be great to update the spconv methods names.

Generally, this work is very helpful to me. Thanks for your great work!

**Comment by xinge008** [comment]
I do not use the spconv >= 2.x and there is no pretrained model for spconv>=2.x; In my opinion, in spconv>=2.0, some basic definitions are changed so you need fit it with some modifications.
