### ISSUE TITLE
Regarding other sparse conv libraries

### ISSUE THREAD

**Issue by akshay-antony** [xinge008/Cylinder3D#138]
Hi, Thanks for the amazing work and concise explanation in the paper. But can I use other sparse Conv libraries like ME, or torch sparse or is there any reason for using spconv. And is spconv tensorrt compatible?

**Comment by xinge008** [comment]
We follow the popular setting in 3D detection (like SECOND, PointPillar) to use the spconv as the basic block; Other sparse convs may work too, while we do not have a try.
