### ISSUE TITLE
Question about tta

### ISSUE THREAD

**Issue by iris0329** [xinge008/Cylinder3D#15]
Thanks for you opening-source of this project !

But I can't search **tta** in google, what is **tta**?

Looking forward to your reply.

> 目前我们只提供了满足val上结果的pretrain模型，test上的结果还需要进一步的后处理，包括tta，finetuning with validation等。
_Originally posted by @xinge008 in https://github.com/xinge008/Cylinder3D/issues/14#issuecomment-758344309_

**Comment by xinge008** [comment]
TTA denotes Test time augmentation, which is commonly used in the Kaggle competition. You can find the reference in the following URLs

https://www.kaggle.com/andrewkh/test-time-augmentation-tta-worth-it
https://machinelearningmastery.com/how-to-use-test-time-augmentation-to-improve-model-performance-for-image-classification/
https://towardsdatascience.com/test-time-augmentation-tta-and-how-to-perform-it-with-keras-4ac19b67fb4d

**Comment by iris0329** [comment]
Thanks for your reply!
