### ISSUE TITLE
Bad Result at demo_folder.py

### ISSUE THREAD

**Issue by DonghoonPark12** [xinge008/Cylinder3D#152]
I tested based on https://github.com/L-Reichardt/Cylinder3D_spconv_v2 repo. Cause I use CUDA 11.3 and Spconv1.x is deprecated.

I run demo_folder.py and I got below result which is embarrassing.

```
matched parameter sets: 226, and no matched: 48

Validation per class iou: 
car : 0.00%
bicycle : 0.00%
motorcycle : 0.00%
truck : 0.00%
bus : 0.00%
person : 0.00%
bicyclist : 0.00%
motorcyclist : 0.00%
road : 0.00%
parking : 0.00%
sidewalk : 0.00%
other-ground : 0.00%
building : 0.00%
fence : 0.00%
vegetation : 30.61%
trunk : 0.00%
terrain : 0.00%
pole : 0.00%
traffic-sign : 0.00%
Current val miou is 1.611
Current val loss is 3.492
```

What did I do wrong??

**Comment by cama36** [comment]
same problem,how to solve it?

**Comment by DonghoonPark12** [comment]
@cama36 https://github.com/L-Reichardt/Cylinder3D_spconv_v2. In here author upload new WEIGHT. You can refer to it.

and you can expect below result which is slight lower performance than original paper.

```
Validation per class iou:
car : 96.92%
bicycle : 54.25%
motorcycle : 80.25%
truck : 33.20%
bus : 69.36%
person : 45.18%
bicyclist : 59.40%
motorcyclist : 51.25%
road : 95.75%
parking : 55.55%
sidewalk : 86.47%
other-ground : 0.00%
building : 80.21%
fence : 37.01%
vegetation : 89.62%
trunk : 73.00%
terrain : 80.73%
pole : 73.18%
traffic-sign : 73.67%
Current val miou is 65.000
Current val loss is 0.600
```

**Comment by rohithsaro** [comment]
@DonghunP 
The files in the google drive, though they are .pt file, when downloaded they are a zip folder, how did you get around this ?

Eager to hear from you soon :)

**Comment by ravishankark1992** [comment]
hi @DonghoonPark12 
could you please share the weights for the https://github.com/L-Reichardt/Cylinder3D-updated-CUDA repo? The link seems to be broken. 
Thanks

**Comment by Jeffgit2022** [comment]
I met with similar problem

(com88) adminpc@adminpc-B760-DS3H:/media/adminpc/828F225A817AD4FA/Cylinder3D$ python demo_folder.py  --demo-folder ./dataset/sequences/00/velodyne/ --save-folder ./model_save_dir --demo-label-folder ./dataset/sequences/00/labels/
......
save ./model_save_dir/000000.label
save ./model_save_dir/000001.label
save ./model_save_dir/000002.label
......
save ./model_save_dir/004539.label
save ./model_save_dir/004540.label
Validation per class iou: 
car : 0.00%
bicycle : 0.00%
motorcycle : 0.00%
truck : 0.00%
bus : 0.24%
person : 0.00%
bicyclist : 0.00%
motorcyclist : 0.00%
road : 0.00%
parking : 0.00%
sidewalk : 0.00%
other-ground : 0.00%
building : 0.00%
fence : 0.00%
vegetation : 0.00%
trunk : 0.00%
terrain : 0.00%
pole : 0.00%
traffic-sign : 0.00%
Current val miou is 0.013
Current val loss is 3.951

**Comment by Sylva-Lin** [comment]
> @cama36 https://github.com/L-Reichardt/Cylinder3D_spconv_v2. In here author upload new WEIGHT. You can refer to it.
> 
> and you can expect below result which is slight lower performance than original paper.
> 
> ```
> Validation per class iou:
> car : 96.92%
> bicycle : 54.25%
> motorcycle : 80.25%
> truck : 33.20%
> bus : 69.36%
> person : 45.18%
> bicyclist : 59.40%
> motorcyclist : 51.25%
> road : 95.75%
> parking : 55.55%
> sidewalk : 86.47%
> other-ground : 0.00%
> building : 80.21%
> fence : 37.01%
> vegetation : 89.62%
> trunk : 73.00%
> terrain : 80.73%
> pole : 73.18%
> traffic-sign : 73.67%
> Current val miou is 65.000
> Current val loss is 0.600
> ```

Can you provide us with the trained model? The download link for the previous weight model is no longer valid.
