### ISSUE TITLE
Checkpoint with spconv2 for nuscenes dataset

### ISSUE THREAD

**Issue by chucktang98** [xinge008/Cylinder3D#155]
Can you guys release a checkpoint with spconv2 for the nuScenes dataset? That would be greatly appreciated

**Comment by L-Reichardt** [comment]
Currently, from my knowledge the authors are sticking to Spconv1. There is an [open issue](https://github.com/xinge008/Cylinder3D/issues/107) on the spconv-v2.x topic, however everyone has been retraining by themselves (for Semantic-KITTI, but maybe someone else has a nuScenes checkpoint)
