### ISSUE TITLE
About shared memory

### ISSUE THREAD

**Issue by whu-lyh** [xinge008/Cylinder3D#17]
Hi xinge，thanks for your amazing work and your code shared. While i train the cylinder_asym, an error about shared memory limited occurs. So i wander what size of shared memory you suggested while training? BTW, i am training on docker and only one 1080Ti available.

**Comment by whu-lyh** [comment]
Maybe the num_workers should be 0 ...

**Comment by xinge008** [comment]
You can change the batch_size = 1 when you use 1080Ti; 

For limited shared memory, you can set num_workers=0 or enlarge the quota of shared memory.
