### ISSUE TITLE
Details request

### ISSUE THREAD

**Issue by bhaba-ranjan** [xinge008/Cylinder3D#171]
For NuScenes dataset, I see this in the readme.md file

1. Pre-processing: we follow the data pre-processing in SECOND to prepare the nuscenes_info file, including nuscenes_infos_train.pkl, nuscenes_infos_val.pkl and nuscenes_infos_test.pkl. 

Can someone please help me understand how this files are created? is there another repository with the code ref to generate this files?

**Comment by YEOMJINSEOP** [comment]
Did you figure out?

**Comment by bhaba-ranjan** [comment]
Negative @YEOMJINSEOP
