### ISSUE TITLE
About training parameters?

### ISSUE THREAD

**Issue by iris0329** [xinge008/Cylinder3D#18]
Thanks for sharing this brilliant work.

I found in the code that the batch size is 2 but training is based on the  only one GPU.

I wonder what is the real batch size that could reprodece the best result in your paper.

I am looking forward to your reply.

**Comment by xinge008** [comment]
We use V100 GPU with 16G memory to train the model, and the batch size is 2; It is better to set batch size=2 to get the results reported in the paper.

**Comment by iris0329** [comment]
Thank you
