### ISSUE TITLE
Baseline architecture

### ISSUE THREAD

**Issue by daniel-scholz** [xinge008/Cylinder3D#19]
Hello, 

I was reading your paper and quite intrigued by the new method you came up with! 
However, I am quite surprised by your UNet-baseline achieving 61.5% mIoU on KITTI.  
Would you mind sharing your architecture and training details for the baseline?

Best,
Daniel

**Comment by xinge008** [comment]
Our baseline utilizes the cubic partition and regular 3d conv. For cubic partition, the dataloader provides its implementation. BTW, it achieves 60.8 on the semantickitti val set

**Comment by daniel-scholz** [comment]
Thanks for your answer!
