### ISSUE TITLE
The division of Semantic Kitti data.

### ISSUE THREAD

**Issue by zxczrx123** [xinge008/Cylinder3D#2]
Thank you for your work. I'm wondering if you process the entire 100mx100mx10m input directly during training or do you need to pre-divide it like other networks (e.g. PointASNL is first divided into 10mx10mx6m)?I think your polar based 3D division is directly applied to the whole scan, I don't know if that's right.

**Comment by xinge008** [comment]
Yes, the cylinder partition is performed on the whole pointcloud.
