### ISSUE TITLE
Inference on CPU

### ISSUE THREAD

**Issue by abhigoku10** [xinge008/Cylinder3D#20]
@xinge008  thanks for sharing the code i have few queries 
1.Can we run the inference pipeline on the CPU , what are the modifications required to run it in the cpu 
2.what is the latency time in cpu and gpu 
THanks in advance

**Comment by xinge008** [comment]
1. I do not have a try on CPU. Maybe some requirements are not suitable such as Torch_scatter. You can modify them based on the Error Log if appeared.

2. For gpu inference, the average time is about 170ms with V100 GPU for one point cloud in SemanticKITTI.

**Comment by abhigoku10** [comment]
@xinge008 to run a single point cloud and to obtain the inference details of the pipeline  can we use the PolarSeg repo? do u follow the similar code base ??

**Comment by xinge008** [comment]
yes, you can.

**Comment by abhigoku10** [comment]
@xinge008 yes i have completed that part , but when I test the model I am not getting the expected results I have raise an issue #21 please share your views on this

**Comment by abhigoku10** [comment]
@xinge008  thanks for the support now i am able to run on the cpu
