### ISSUE TITLE
Trained Model output resutl error 

### ISSUE THREAD

**Issue by abhigoku10** [xinge008/Cylinder3D#21]
@xinge008  Hi i ran the inference module using the shared pretrained model and I am obtaining the results as shown below 
![image](https://user-images.githubusercontent.com/22094053/107660802-a8617280-6cae-11eb-8ed8-ee8f4d377704.png)

My environment is python=3.6 pytorch=1.7 cuda=10.1 spconv=1.2.1 , can you let me know the exact versions which the model had been trained on . THanks in advance

**Comment by YoushaaMurhij** [comment]
Are you using RVIZ? Can you also show the GT?

**Comment by abhigoku10** [comment]
@YoushaaMurhij @xinge008  i am using pptk viewer to look into the annotations and predictions of semantic kitti data , below is the gt and right is predictions
![image](https://user-images.githubusercontent.com/22094053/108010373-b7d41900-702a-11eb-8468-3be0e3b4060e.png)

**Comment by YoushaaMurhij** [comment]
It feels like you have a color encoding problem .. no more, when converting the labels to colors.
Could u check that?

**Comment by abhigoku10** [comment]
@YoushaaMurhij  i am using the saving code from polar seg repo , 

            # write to label file
            for count,i_test_grid in enumerate(test_grid):
                test_pred_label = predict_labels[count,test_grid[count][:,0],test_grid[count][:,1],test_grid[count][:,2]]
                test_pred_label = train2SemKITTI(test_pred_label)
                test_pred_label = np.expand_dims(test_pred_label,axis=1)
#                 save_dir = test_dataset_loader.im_idx[test_index[count]]
                _,dir2 = filename[0].split('/sequences/',1)
                new_save_dir = output_path + '/sequences/' +dir2.replace('velodyne','predictions')[:-3]+'label'                
                if not os.path.exists(os.path.dirname(new_save_dir)):
                    try:
                        os.makedirs(os.path.dirname(new_save_dir))
                    except OSError as exc:
                        if exc.errno != errno.EEXIST:
                            raise
                test_pred_label = test_pred_label.astype(np.uint32)
                test_pred_label.tofile(new_save_dir)

            ##### To check the predicted results 
            for count, i_test_grid in enumerate(test_grid):
                hist_list.append(fast_hist_crop(predict_labels[
                                count, test_grid[count][:, 0], test_grid[count][:, 1],
                                test_grid[count][:, 2]], test_pt_labs[count],
                            unique_label))

This is the code i use to save the predictions

**Comment by abhigoku10** [comment]
@YoushaaMurhij  yes your correct, there was issue in the color encoding , thanks for point it out currently have resolved this issue now getting correct output

**Comment by muzi2045** [comment]
how to get the visual results from raw network output?
the Cylinder3D network get [1, 480, 360, 32] input, and output is  [1, 20, 480, 360, 32] torch tensor
```
res = model(train_pt_fea_ten, train_vox_ten, batch_size)
 
predicted_labels =  torch.argmax(res, dim=1) 

```

@abhigoku10  @YoushaaMurhij

**Comment by abhigoku10** [comment]
@muzi2045  i am actually saving the labels and then using semantic kitti code base to view the predicitions please find the reference which worked for me https://github.com/edwardzhou130/PolarSeg/blob/master/test_pretrain_SemanticKITTI.py

**Comment by muzi2045** [comment]
thanks a lot, I'll try it.

**Comment by muzi2045** [comment]
with the semantic-kitti api codebase, here is some result output:
![image](https://user-images.githubusercontent.com/12984898/109122540-b8d01d80-7783-11eb-9c34-9cf9bc996f17.png)
![image](https://user-images.githubusercontent.com/12984898/109122582-c685a300-7783-11eb-87eb-3941eb4509e7.png)

why the road points are colored as black? 
maybe the color map need to be change or something wrong when generate the points label file.
@abhigoku10

**Comment by abhigoku10** [comment]
@muzi2045  you have to use proper color map during saving and visualization

**Comment by zhaodejian** [comment]
> @muzi2045 i am actually saving the labels and then using semantic kitti code base to view the predicitions please find the reference which worked for me https://github.com/edwardzhou130/PolarSeg/blob/master/test_pretrain_SemanticKITTI.py

when i use the same code as you, i got the error "ValueError: Input must be 1- or 2-d."---do you know what the problems ?
```
(pytorch) ziudarkin@ziudarkin-ubuntu:~/PolarSeg$ python train_SemanticKITTI.py
train_SemanticKITTI.py
Namespace(check_iter=4000, data_dir='data', grid_size=[480, 360, 32], model='polar', model_save_path='./SemKITTI_PolarSeg.pt', train_batch_size=2, val_batch_size=2)
  0%|                                                   | 0/136 [00:00<?, ?it/s]Traceback (most recent call last):
  File "train_SemanticKITTI.py", line 197, in <module>
    main(args)
  File "train_SemanticKITTI.py", line 129, in main
    iou = per_class_iu(sum(hist_list))
  File "train_SemanticKITTI.py", line 27, in per_class_iu
    return np.diag(hist) / (hist.sum(1) + hist.sum(0) - np.diag(hist))
  File "<__array_function__ internals>", line 6, in diag
  File "/home/ziudarkin/anaconda3/envs/pytorch/lib/python3.7/site-packages/numpy/lib/twodim_base.py", line 303, in diag
    raise ValueError("Input must be 1- or 2-d.")
ValueError: Input must be 1- or 2-d.
  0%|                                                   | 0/136 [00:01<?, ?it/s]
```
