### ISSUE TITLE
Point-Wise Refinement Module Missing

### ISSUE THREAD

**Issue by JBKnights** [xinge008/Cylinder3D#23]
Hello,

After looking through the code I can't seem to find where the point-wise refinement module has been implemented; is this currently in the codebase, or is it currently absent?

Thanks,
Joshua

**Comment by xinge008** [comment]
Yes, the current version of codebase is the preliminary version. There is no point-wise refinement module. In fact, the PR module makes a smaller contribution compared to cylinder partition and asymmetrical conv. Hence, we first release these crucial components.
