### ISSUE TITLE
Nuscenes Minidataset

### ISSUE THREAD

**Issue by abhigoku10** [xinge008/Cylinder3D#24]
@xinge008  Thanks for sharing the code base i have the following queries 

1.To generate the .pkl files  should we always use SECOND code base as you have mentioned 
2.To save the  predictions along with label should we follow the same steps mentioned in polar seg ?

Support will be highly appreciated !!!

**Comment by xinge008** [comment]
To save the prediction, you can refer this [line](https://github.com/xinge008/Cylinder3D/blob/7df59464c9b1828f9f97084997b3d47beda612cd/train_cylinder_asym_nuscenes.py#L98-L99). In this way, you can obtain the prediction.

**Comment by abhigoku10** [comment]
@xinge008  i have used the same method but for visualisation of nuscenes we need to color code it similar to semanttick kitti

**Comment by xinge008** [comment]
For color coding, you can refer to the color mapping in [SemanticKITTI](https://github.com/xinge008/Cylinder3D/blob/master/config/label_mapping/semantic-kitti.yaml)
