### ISSUE TITLE
code on 2D backbone

### ISSUE THREAD

**Issue by timelapse3502** [xinge008/Cylinder3D#25]
In Section 4.2 of the [Cylinder3D](https://arxiv.org/pdf/2008.01550.pdf) paper, it was mentioned that 'cylinder3d voxelization + our 2d backbone' still achieves a good performance. I wonder how 2d backbone is implemented. The paper says 3d backbone uses 3d conv while 2d backbone uses 2d conv, but what about the asymmetircal residual block and DDCM?

**Comment by xinge008** [comment]
When implementing the 2D backbone, our cylinder3D performs a 2D transformation following PointPillar, from 3D space to bird-view representation, and then use the 2D conv to stack the 2D backbone. For asymmetrical block and DDCM, they are all implemented in 2D space.

**Comment by timelapse3502** [comment]
Thanks for your explanation. Is there any plan to release the code of 2D backbone? I'm trying to deploy this model onboard but unfortunately spconv is not convertible with TensorRT, so I would have to employ the 2D backbone.

**Comment by xinge008** [comment]
The key difference is the 3D-2D transformation, and you can follow this [code](https://github.com/traveller59/second.pytorch/blob/3aba19c9688274f75ebb5e576f65cfe54773c021/second/pytorch/models/pointpillars.py#L421-L476) to function it.

**Comment by timelapse3502** [comment]
I'm familiar with the PointPillar 3D-2D transformation. Could you elaborate more on what would asymmetrical block and DDCM look like in 2D?
![Screen Shot 2021-03-01 at 9 04 00 PM](https://user-images.githubusercontent.com/79657776/109590505-b5b19600-7ad1-11eb-8def-f8dc430aaaee.png)

**Comment by xinge008** [comment]
For asymmetrical block, its shape looks like 3x1 and 1x3 and no third dimension. For DDCM, you can refer to this [paper](https://arxiv.org/pdf/2008.00490).

**Comment by timelapse3502** [comment]
That's super help, thanks!
