### ISSUE TITLE
multiscan iou 低于 single scan

### ISSUE THREAD

**Issue by caoyifeng001** [xinge008/Cylinder3D#26]
你好， 为什么multiscan iou 会低于 single scan

**Comment by xinge008** [comment]
Due to more moving categories (refer to the leaderboard), multiscan segmentation is harder than single-scan.

**Comment by Shaoqing26** [comment]
> Due to more moving categories (refer to the leaderboard), multiscan segmentation is harder than single-scan.

Xinge,I send u an gmail,Can u take a look if u have any time?

**Comment by caoyifeng001** [comment]
还有一个问题，验证集没有pose信息需要怎么办呢

**Comment by xinge008** [comment]
The test set also contains the calib.txt and poses.txt

**Comment by caoyifeng001** [comment]
好的我找到了
