### ISSUE TITLE
当batch_size>1时，不同batch的点一起输入到MLP？

### ISSUE THREAD

**Issue by Goodtasterr** [xinge008/Cylinder3D#27]
Cylinder3D/network/cylinder_fea_generator.py
line77: processed_cat_pt_fea = self.PPmodel(cat_pt_fea)
当batch_size>1时，cat_pt_fea是不同batch的点shuffle后的集合。
不同batch的点经过shuffle后一起输入到MLP？这样是否有问题？

**Comment by xinge008** [comment]
因为batchid已经concat到index里面，所以不同batch的点也可以进行shuffle，可以通过index来定位点属于哪个batch

https://github.com/xinge008/Cylinder3D/blob/master/network/cylinder_fea_generator.py#L60-L61
