### ISSUE TITLE
Model inference time?

### ISSUE THREAD

**Issue by zeyu-hello** [xinge008/Cylinder3D#3]
Hi @xinge008 

Thanks for your brailliant work. 
One thing I'm curious is how the memory occupacy and inference time of this Cylinder3D model with 10w points input?

Best Regards!

**Comment by xinge008** [comment]
Hi, zeyu,

Thanks for your attention.

For memory occupancy, it costs about 6G memory for a point cloud in SemanticKITTI. For inference time, we do not make a statistic now. We will make a detailed comparison in the future.

Best,
Xinge

**Comment by zeyu-hello** [comment]
Roughly, can it reach 10Hz when you test with torch model?

**Comment by xinge008** [comment]
Thanks for your try. We will give a comparison in the future.

**Comment by abhigoku10** [comment]
@zeyu-hello  do u have the inference code to test the pre-trained model
