### ISSUE TITLE
test.py

### ISSUE THREAD

**Issue by libozan** [xinge008/Cylinder3D#31]
@xinge008 Thank you so much for sharing the code.

I am currently implementing your code repeatedly. Due to the limitation of 2080Ti, the memory during training is not enough and the batch size can only be set to 1. I want to test my training results and consider whether it needs to be implemented on 3090, but I did not find a test .py file, I don’t know if I can use PolarSeg/test_pretrain_SemanticKITTI.py to test.

**Comment by xinge008** [comment]
For inference on SemanticKITTI or nuScenes, you can refer code in  https://github.com/xinge008/Cylinder3D/blob/master/train_cylinder_asym.py#L82-L107;

BTW, you can also use  PolarSeg/test_pretrain_SemanticKITTI.py with some modification;

**Comment by libozan** [comment]
thank you very much for your help.
