### ISSUE TITLE
tee: logs_dir/cylinder_asym_networks_logs_tee.txt: No such file or directory ?

### ISSUE THREAD

**Issue by mandal4** [xinge008/Cylinder3D#33]
Thanks for releasing the codes.
With following your instruction, i ran the train.sh script.
And i found following message, but the code is still working thankfully.
Is there more setting that i miss?

Further, what does the bar mean? ( 245 / 4247 )
'4247' means number of scans per epoch? 

![image](https://user-images.githubusercontent.com/34879386/111753489-45c94b00-88da-11eb-8539-4521331d22c9.png)

**Comment by RESET0** [comment]
Just make a folder named `logs_dir` by yourself.

**Comment by xinge008** [comment]
@mandal4 

The comments of @RESET0 are totally right.
