### ISSUE TITLE
What defines input value?

### ISSUE THREAD

**Issue by mandal4** [xinge008/Cylinder3D#36]
I found that the dimension for the both inputs, train_pt_fea_ten: [126804,9], train_vox_ten: [126804,3]
I guess the 126804 represents the number of points, and i want to figure out what define both '9' and '3'.

Thanks,

**Comment by xinge008** [comment]
For train_pt_fea_ten, the input features are defined in [this line](https://github.com/xinge008/Cylinder3D/blob/master/dataloader/dataset_semantickitti.py#L120); 

For train_vox_ten, it contains the coordinates of point, defined in [this line](https://github.com/xinge008/Cylinder3D/blob/master/dataloader/dataset_semantickitti.py#L96);
