### ISSUE TITLE
Explain Cylindrical Projection

### ISSUE THREAD

**Issue by FrancescoMandru** [xinge008/Cylinder3D#40]
I'm really interested in running some test of you cylindrical projection with non cylindrical voxeling but I'm struggling finding where do you use the vexels classes in you code. If I would like to apply your cylindrical voxelization only how can I do? To be clear I know how to do cylindrical projection, I'm interested in the cylindrical partition and how it works in detail and also where is done on your code, I suppose is this part here  from 230

https://github.com/xinge008/Cylinder3D/blob/6dfbbfa0ea44f1f0196951f139e756cbea5205bb/dataloader/dataset_semantickitti.py#L230

but it's not clear what are you doing both for points and labels as in the paper there is no appendix regarding math operations and the repo is not well documented. 

Thank you in advance

**Comment by xinge008** [comment]
In [dataloader](https://github.com/xinge008/Cylinder3D/blob/master/dataloader/dataset_semantickitti.py#L230-L259), the transformed cylindrical coordinates, point-voxel mapping, voxel_label ("processed_label") are provided.  Cylindrical partition is performed via first transforming the coordinate to cylinder coordinate and then aggregating these point-wise features within same voxel (https://github.com/xinge008/Cylinder3D/blob/master/network/cylinder_fea_generator.py#L78)

If you want to probe the details of code, it is better to run it step by step and see its output.

**Comment by FrancescoMandru** [comment]
Hi @xinge008 thanks for your reply. I'm actually interested in the mathematical steps to obtain a cylindrical voxelization. I will dive into the code for sure but it's hard to understand what the code does if I don't know the theoretical part behind it
