### ISSUE TITLE
Cannot find point-wise prediction and loss function.

### ISSUE THREAD

**Issue by mandal4** [xinge008/Cylinder3D#42]
Thanks for sharing your kind code.
Unfortunately i couldn't find out the code about point-wise prediction and corresponding loss function.
I found out the output of model is [#bs, 20, 480,360,32] which is a form of voxel.
And the corresponding loss is calculated with voxel-wise class label.

Where can i find the lines about point-wise prediction and corresponding loss function?

Thanks,

**Comment by FrancescoMandru** [comment]
Maybe is not implemented yet

https://github.com/xinge008/Cylinder3D/issues/8#issuecomment-737069254

**Comment by JBKnights** [comment]
The point-wise predictions can be found in the validation loop - you can see that the grid is used to re-project from the voxels to the point cloud

In the current implementation there isn't a point-wise refinement module; all the losses take place purely on a voxel level.
