### ISSUE TITLE
Expected mIoU of the pretrained checkpoint

### ISSUE THREAD

**Issue by JBKnights** [xinge008/Cylinder3D#44]
Hello,

Would you be able to tell us what the expected mIoU of the pretrained checkpoint you supply should be?  In the environment I'm using I got a mIoU of 66.914, which is significantly higher than what you report in your paper.  Some clarification on why that might be the case would be very helpful.

Thanks!
![image](https://user-images.githubusercontent.com/47620360/113254635-33073b00-930a-11eb-8c96-11e597c604cf.png)

**Comment by xinge008** [comment]
The model provided in the codebase is slight higher than original paper after more training epochs.

**Comment by owoshch** [comment]
Hi @JBKnights! I'm trying to reproduce the results you posted. Could you please share the command you ran to obtain those results?
Thank you!

**Comment by GaloisWang** [comment]
excuse me, when I test the pretrained model on KITTI 08 sequence, the results are all 0. Have you encountered this problem before？
