### ISSUE TITLE
A question 

### ISSUE THREAD

**Issue by jediofgever** [xinge008/Cylinder3D#45]
Hello ,
I have read through the paper. The work looks fantastic. 
I was wondering whether this network is particularly suiting for my needs or its an overkill. 

I have a pointcloud map that is automatically generated and labeled from simulation. I sematic segment the cloud to two class, ground and non-ground. 
 The cloud doesn't have the features of LIDAR pointcloud such as sparsity in distant regions. My cloud is uniformly sampled almost equal density at any point, 
will this method(Cylinder3D ) still output state-of-the-art results for such a case ? 

whats your thoughts ? 

Thank you very much

**Comment by xinge008** [comment]
In my opinion, you can use cylinder3D as the backbone network; 

For your specific settings, ie, two-categories and closed relationship with height, you can design some modules to explore the geometric information (such as height) or design some specific loss functions. Just my two cents.
