### ISSUE TITLE
Help with the point refinement module

### ISSUE THREAD

**Issue by JBKnights** [xinge008/Cylinder3D#48]
Hello,

I'm trying to implement the point refinement module following your instructions in previous issue posts, but my attempts have all resulted in stark drop in performance for the final network.  Would it be possible for you to provide screencaps of how your unreleased code:
a) Gets features from the earlier linear layers (PPModel in cylinder_fea_generator) to pass to the refinement module
b) Defines the layers in the refinement module
c) Integrates the refinement module in the forward pass

If you could do this it would be a massive help!  Thanks!

**Comment by xinge008** [comment]
You can refer to https://github.com/xinge008/Cylinder3D/issues/28 .

**Comment by JBKnights** [comment]
Thanks for the quick response!

The reason I'm asking this is that I've tried implementing using the instructions in the link you've sent, but I'm still seeing a drop in performance - I'm not sure where what I'm doing is diverging from your approach, so the additional insight from any screenshots you could provide would be super helpful in replicating your approach

**Comment by xinge008** [comment]
I suggest the model with point refinement requires more training epochs. 
Maybe you can give it a longer time. 

To be honest, batch_size=2 can give a slightly better performance if it is feasible.

**Comment by L-Reichardt** [comment]
@JBKnights Did you ever find the issue? I am facing the same problem, suspecting it is caused by how the data is shuffled in PPmodel (from what I understand maxpooling / Spconv somewhat reorganizes it). I am using the unshuffled data for the skip connection. Model converges after 15 epochs.
