### ISSUE TITLE
Exact Environment Information

### ISSUE THREAD

**Issue by vaydingul** [xinge008/Cylinder3D#51]
Hey @xinge008 ,

Can you have a chance to tell me the exact environment information while working on this project? Currently, I am trying to run this model in an HPC cluster, however, it seems that the combination of spconv, torch, and torch-scatter is very sensitive. Meaning that their compatible CUDA version and etc. create a lot of headaches. However, I believe I can replicate your results, if I may know your system information since I will be able to install exact dependencies. 

By the way, I really like to express that it is an amazing project, I sincerely congratulate you and I wish you the continuation of this success.

Thanks in adcanve.

**Comment by xinge008** [comment]
For spconv , we use spconv==1.2.1 and cuda==10.2;
torch-scatter >= 1.4.0
torch==1.2.

**Comment by vaydingul** [comment]
Thank you very much really. Can you also elaborate on your CUDA-cuDNN and Python versions?

**Comment by xinge008** [comment]
python==3.7.7
cuDNN==7.6.5
cuda==10.2
