### ISSUE TITLE
DDCM Module

### ISSUE THREAD

**Issue by Youngsplace0913** [xinge008/Cylinder3D#52]
First of all, thank you for releasing such a good work!

1. Where is the part corresponding to the DDCM module in the code?
2. And can you explain this in a little more detail?
3. And what is the role of height pooling? Is there a reference?
4. Finally, in the up model, why did not you use dropout at the end?

Thank you so much.

**Comment by xinge008** [comment]
1. For DDCM, please refer to [this part](https://github.com/xinge008/Cylinder3D/blob/master/network/segmentator_3d_asymm_spconv.py#L215-L246).

2. Detailed structure is shown in [paper](https://arxiv.org/pdf/2011.10033).

3. Height pooling controls the switch of height pooling (open means performing the pooling on height-dimension).

4. In my initial attempt, dropout gives a slightly worse performance; I remove them all.

**Comment by Youngsplace0913** [comment]
Thank you so much for answering quickly!

Finally, can't you provide a code to determine whether or not the empty Voxel is available?
I would like to draw a graph that the cylinder has fewer empty cells than the standard voxel.

Thank you.
