### ISSUE TITLE
Training the model using multiple onboard GPUs?

### ISSUE THREAD

**Issue by Ammartauqir** [xinge008/Cylinder3D#53]
First, thank you for publishing the great work. 
In order to enhance the speed of training, do you plan to optimize the training loop such that it can make use of multiple GPUs in the system? 
I have 3 GPUs(Nvidia 1080ti) in my system. I am trying run the training on multiple GPUs using torch.nn.dataParallel() but am ending up with batch_size mismatch error. Can you please guide me through that?
Thank you
Best Regards

**Comment by xinge008** [comment]
you can refer to this issue https://github.com/xinge008/Cylinder3D/issues/22

**Comment by Ammartauqir** [comment]
Thanks a lot for the lead.
