### ISSUE TITLE
Is using pretrained models helpful?

### ISSUE THREAD

**Issue by alrzmshy** [xinge008/Cylinder3D#55]
Hello,

Thanks for making your code publicly available. I'm a bit new to the 3D world. I was wondering if you have tried using pre-trained models for your trainings. In the paper you, give the results on two datasets. Does it help if you start the training on one dataset with weights from the training on the the other?  

I don't see using pre-trained models in 3D papers so that's why I'm curious.

Thank you.

**Comment by xinge008** [comment]
Due to these two datasets with consistent scenes and semantic categories, pretrained models can perform a faster convergence. Just my two cents.
