### ISSUE TITLE
nuScenes dataset

### ISSUE THREAD

**Issue by Youngsplace0913** [xinge008/Cylinder3D#56]
Hello! Thank you so much for the code release.

I have two questions!
1. Did you use full data from the nuScenes dataset or did you use the mini version?

2. Also, Can you explain what parameters can be used to obtain non-empty cells in Figure.3?

**Comment by xinge008** [comment]
Sorry for the late reply.

1. we use full data from nuScenes
2. For cylinder partition, its shape is 480*360; For cubic partition, its voxel size is 0.12 * 0.12
