### ISSUE TITLE
expected input batch_size (6) to match target batch_size (2) 

### ISSUE THREAD

**Issue by caoyifeng001** [xinge008/Cylinder3D#58]
when i use batch size = 6  for train get error 
![image](https://user-images.githubusercontent.com/35130015/119217589-c7716b00-bb0d-11eb-9fa2-a2796c41f13d.png)

**Comment by Colin97** [comment]
Hi @caoyifeng001 , How do you solve this?

**Comment by caoyifeng001** [comment]
训练集最后一组数据不到batch size的大小，只需要`predict_labels = my_model(val_pt_fea_ten, val_grid_ten, val_batch_size)` 改成 `predict_labels = my_model(val_pt_fea_ten, val_grid_ten, val_label_tensor.shape[0])` 就可以了。
