### ISSUE TITLE
performance about nuscenes

### ISSUE THREAD

**Issue by jackmsye** [xinge008/Cylinder3D#66]
hi thanks for your great work. I am wondering about the validation performance of nuscenes dataset. or can your provide me the training logs of nuscenes.

**Comment by xinge008** [comment]
The performance on nuScenes validation set  of Cylinder3D is 76.1 and the performance on testset is shown in the [leaderboard](https://www.nuscenes.org/lidar-segmentation?externalData=all&mapData=all&modalities=Any)
