### ISSUE TITLE
cylinder_dataset和polar_dataset

### ISSUE THREAD

**Issue by Holidays1999** [xinge008/Cylinder3D#68]
您好，在您的代码中，似乎polar_dataset和cylinder_dataset没有什么不同
请问是我看漏了哪些关键的地方吗

**Comment by caoyifeng001** [comment]
多了旋转的噪声的数据增强，大佬工大那个学院的，什么时候带带我。

**Comment by zjuter0126** [comment]
感谢回复，怪不得看起来觉得似乎数据表示上都是把xy变成了极坐标表示。网安那边的

**Comment by caoyifeng001** [comment]
能加个微信吗？15967565899
