### ISSUE TITLE
nuScenes configurations release plan?

### ISSUE THREAD

**Issue by rancheng** [xinge008/Cylinder3D#7]
Hi Xinge, 

Thanks for releasing your code, awesome work! Do you have any plan to release the nuScenes dataset configurations?

**Comment by xinge008** [comment]
Hi, @rancheng,

Thanks for your interest. I am finetuning the model to pursue a more competitive result for nuScenes, and will release the code and model ASAP.  Thanks.

**Comment by YoushaaMurhij** [comment]
Are you planning to release the model weights for nuScenes dataset?

**Comment by abhinavagarwalla** [comment]
Are you planning to release the model config/weights for nuScenes dataset?
Following the NUSCENES-GUIDE, I found a nuscenes model that seems to be trained on a polar projection rather than cylindrical. Is that the case?

**Comment by xinge008** [comment]
The weights released in NUSCENES-GUIDE are Cylinder3D based model. Please check it.
