### ISSUE TITLE
the performance on different resolution dataset

### ISSUE THREAD

**Issue by ImogenHua** [xinge008/Cylinder3D#72]
Hi, thanks for the amazing approach.
i'am trying the prediction by using kitti pretrained model recently.
i use it on my dataset which is collected by 128-beam sensor, but the result seems not well.
![image](https://user-images.githubusercontent.com/49429127/129450738-7ad9c986-4068-4325-84f2-b9ff919fe740.png)

do you have any idea about it?
thanks a lot!

**Comment by xinge008** [comment]
Different beams make a big domain gap. It is better to finetune the pretrained model with 128-beam data if you have some labelled data.
