### ISSUE TITLE
NuScenes multiple sweeps

### ISSUE THREAD

**Issue by ShengyuH** [xinge008/Cylinder3D#74]
hi,

Congrats on this good work. 

I am recently checking NuScene Lidarseg benchmark, according to its official instructions, we are allowed to used up to 10 past sweeps to density the point clouds and hopefully achieve better perception. However, if I understand your codebase correctly, you only use the key frame and also achieve competitive performance(ranked 4th). Did you try models with accumulated point clouds and what’s your experience with it? I know that on semanticKITTI they distinguish between moving and non-moving counterparts and is more challenging, but I think on NuScene, we are penalised less? Or?

Best,
Shengyu

**Comment by xinge008** [comment]
In fact, I do not try to fuse multiple sweeps in NuScene dataset. All these results are obtained via single key frame. 

Generally, fusing multiple sweeps may benefit these tailed classes in the instance level, and copy-paste technique maybe a good alternative.

**Comment by ShengyuH** [comment]
okay great, thanks.
