### ISSUE TITLE
nuscenes dataset

### ISSUE THREAD

**Issue by Allianc-rgb** [xinge008/Cylinder3D#86]
谢谢你的工作！我从中受益很多。有个问题：请问nuscenes数据集是如何划分训练集和验证集呢？我知道下载了相关的pkl文件，并依次划分，或者说这些文件是如何得到的呢？

**Comment by xinge008** [comment]
nuScenes数据集自带官方的划分，你可以看https://github.com/nutonomy/nuscenes-devkit来找分别有哪些scene

**Comment by Allianc-rgb** [comment]
> nuScenes数据集自带官方的划分，你可以看https://github.com/nutonomy/nuscenes-devkit 来找分别有哪些scene
谢谢！
