### ISSUE TITLE
使用GPU训练的问题以及如何使用pretrained model测试

### ISSUE THREAD

**Issue by ferrari700** [xinge008/Cylinder3D#89]
你好，很抱歉打扰您！
                  1.我在使用单张3090进行训练时，看起来它并没有在执行训练（如下图），是什么原因呢？
                  2.如果我想使用您的pretrained model进行KITTI dataset测试，我该如何修改路径以及执行哪个程序呢？
                 非常感谢！！
![image](https://user-images.githubusercontent.com/72401926/140605095-0e0ebe32-bef9-46d4-8f47-9edaea64022a.png)

**Comment by xinge008** [comment]
1. loss的打印间隔取决于config里面的取值，如果没有报错的话，应该是在训练中；
2. 可以参考 demo_folder.py

**Comment by ferrari700** [comment]
> 1. loss的打印间隔取决于config里面的取值，如果没有报错的话，应该是在训练中；
> 2. 可以参考 demo_folder.py

感谢您的回复！
      1.当我在执行demo_folder.py时，遇到之前training时同样问题，我已经将路径替换为KITTI资料集路径以及我新建的输出文件夹路径，但是看起来GPU并没有在工作，当我训练时改为用CPU训练时却有进度显示（有在工作），您知道是什么原因吗？
      2.我在demo_folder.py及config.py中都没有看到可以设置pretrained model路径的地方，是在哪里修改pretrained model的路径呢？
      非常感谢！抱
![Selection_002](https://user-images.githubusercontent.com/72401926/140644634-ad9fd754-bf9f-4a6c-84d9-ad789d3da7f0.png)
歉！

**Comment by ferrari700** [comment]
> 1. loss的打印间隔取决于config里面的取值，如果没有报错的话，应该是在训练中；
> 2. 可以参考 demo_folder.py

感谢您的回复！
1.当我在执行demo_folder.py时，遇到之前training时同样问题，我已经将路径替换为KITTI资料集路径以及我新建的输出文件夹路径，但是看起来GPU并没有在工作，当我训练时改为用CPU训练时却有进度显示（有在工作），您知道是什么原因吗？
2.我在demo_folder.py及config.py中都没有看到可以设置pretrained model路径的地方，是在哪里修改pretrained model的路径呢？
    非常感谢！抱歉！
![Selection_002](https://user-images.githubusercontent.com/72401926/140644659-5dfd3adb-0dec-45ed-bebc-59d3d7e454f1.png)

**Comment by ferrari700** [comment]
感谢您的回复！
1.当我在执行demo_folder.py时，遇到之前training时同样问题，且输出Runtime error ,我已经将路径替换为KITTI资料集路径以及我新建的输出文件夹路径，当我训练时改为用CPU训练时却有进度显示（有在工作），您知道是什么原因吗？
2.我在demo_folder.py及config.py中都没有看到可以设置pretrained model路径的地方，是在哪里修改pretrained model的路径呢？
非常感谢！抱歉
![Selection_003](https://user-images.githubusercontent.com/72401926/140644943-3dd81e23-072d-4630-a0db-0800515597c1.png)
！

**Comment by ferrari700** [comment]
我的环境是：python 3.8    pytorch 1.7    cuda 10.2    spconv 1.2.1

**Comment by xinge008** [comment]
设置pretrained model 在 https://github.com/xinge008/Cylinder3D/blob/master/config/semantickitti.yaml#L63

这个runtime error应该是跟你的gpu driver版本跟gpu 算力不匹配之类的问题，具体问题可以搜索一下

**Comment by Daisy-GENG** [comment]
这边我试了一下，具体可以看这里：
https://github.com/xinge008/Cylinder3D/issues/77#issuecomment-1006722740

事实上 3090也能跑 就是得试试... 见上链接
