### ISSUE TITLE
how the model speed?

### ISSUE THREAD

**Issue by jinfagang** [xinge008/Cylinder3D#9]
Any speed comparsion with other sota models?

**Comment by xinge008** [comment]
We randomly sample 100 frames from val set, and make a statistic. This method achieves 7.6 fps.

**Comment by jinfagang** [comment]
@xinge008 what's the voxel step you use? How many points used feed into model?

**Comment by xinge008** [comment]
We use all points in the LiDAR frame as the input. For the voxelization, we utilize the proposed cylinder partition, and you can find the details in the dataloader

**Comment by yanx27** [comment]
Hi @xinge008 , thanks for your great work. I trained your codes on a single TITAN XP GPU, and found out that it costs more than 3 hours per epoch. Furthermore, after 5 epochs, it only achieves 9% mIoU.  Is this phenomenon normal? How long does it take for the model to converge when you train?

**Comment by xinge008** [comment]
@yanx27  In our experiment, we use the v100 with 16G memory to train our network, and the batchsize=2. After 5 epochs, it achieves about 47% mIoU. Total training time is about four days with one card.

**Comment by artofstate** [comment]
Hi! @xinge008 ,I use RTX 3090 with 24G memory to train the network.And every iter takes 1.0-1.5s.Is it a normal speed? Is there any idea to improve the speed? It takes me 1 week with batchsize =2,maxch_epoch =50
