### ISSUE TITLE
Question about details

### ISSUE THREAD

**Issue by tongxueqing** [xinge008/Cylinder3D#95]
This is really great work!  And I have some questions:

1Cylindrical Partition:the shape is 480*360*32, how do you get these numbers? Why 32 seem to be bigger than other discretization-based method(like 10 in voxelnet)? 
2.how do you project voxel-wise features to point-wise feature? interpolate with its neighbor voxel grids or naive nearest interpolation?
3.in previous reply, you mention copy-paste technique. Can you explain how to use it in details?
Thanks a lot!

**Comment by xinge008** [comment]
1: the cylindrical partition is 480*360*32; we split it mannully.
2: The projection between voxel and point is based on the voxel coordinate; You can find the details in https://github.com/xinge008/Cylinder3D/blob/master/train_cylinder_asym.py#L103-L106
3: This technique is mainly for the 3D detection; You can find it in SECOND (https://github.com/traveller59/second.pytorch)
